package com._27seconds.holidays.us.dates;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T13:56:07.719+12:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", name = "USHolidayDatesHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface USHolidayDatesHttpPost {

    /**
     * Get the date of Independence Day.
     */
    @WebMethod(operationName = "GetIndependenceDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getIndependenceDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of New Year's Eve.
     */
    @WebMethod(operationName = "GetNewYearsEve")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getNewYearsEve(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Abraham Lincoln's Birthday.
     */
    @WebMethod(operationName = "GetAbrahamLincolnsBirthday")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getAbrahamLincolnsBirthday(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Good Friday.
     */
    @WebMethod(operationName = "GetGoodFriday")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getGoodFriday(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Thanksgiving Day.
     */
    @WebMethod(operationName = "GetThanksgivingDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getThanksgivingDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Halloween Day.
     */
    @WebMethod(operationName = "GetHalloweenDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getHalloweenDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of April Fool's Day.
     */
    @WebMethod(operationName = "GetAprilFoolsDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getAprilFoolsDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Flag Day.
     */
    @WebMethod(operationName = "GetFlagDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getFlagDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Labor Day.
     */
    @WebMethod(operationName = "GetLaborDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getLaborDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Columbus Day.
     */
    @WebMethod(operationName = "GetColumbusDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getColumbusDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Easter.
     */
    @WebMethod(operationName = "GetEaster")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getEaster(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Martin Luther King Day.
     */
    @WebMethod(operationName = "GetMartinLutherKingDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getMartinLutherKingDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Father's Day.
     */
    @WebMethod(operationName = "GetFathersDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getFathersDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Valentines Day.
     */
    @WebMethod(operationName = "GetValentinesDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getValentinesDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of President's Day.
     */
    @WebMethod(operationName = "GetPresidentsDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getPresidentsDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Black Friday.
     */
    @WebMethod(operationName = "GetBlackFriday")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getBlackFriday(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Saint Patrick's Day.
     */
    @WebMethod(operationName = "GetSaintPatricksDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getSaintPatricksDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of New Year.
     */
    @WebMethod(operationName = "GetNewYear")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getNewYear(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Veteran's Day.
     */
    @WebMethod(operationName = "GetVeteransDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getVeteransDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of George Washington's Birthday.
     */
    @WebMethod(operationName = "GetGeorgeWashingtonsBirthday")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getGeorgeWashingtonsBirthday(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Christmas.
     */
    @WebMethod(operationName = "GetChristmasDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getChristmasDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Cinco de Mayo.
     */
    @WebMethod(operationName = "GetCincoDeMayo")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getCincoDeMayo(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Memorial Day.
     */
    @WebMethod(operationName = "GetMemorialDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getMemorialDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );

    /**
     * Get the date of Mother's Day.
     */
    @WebMethod(operationName = "GetMothersDay")
    @WebResult(name = "dateTime", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getMothersDay(
        @WebParam(partName = "year", name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        java.lang.String year
    );
}
