package com._27seconds.holidays.us.dates;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T13:56:07.665+12:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", name = "USHolidayDatesSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface USHolidayDatesSoap {

    /**
     * Get the date of Independence Day.
     */
    @WebMethod(operationName = "GetIndependenceDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetIndependenceDay")
    @RequestWrapper(localName = "GetIndependenceDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetIndependenceDay")
    @ResponseWrapper(localName = "GetIndependenceDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetIndependenceDayResponse")
    @WebResult(name = "GetIndependenceDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getIndependenceDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of New Year's Eve.
     */
    @WebMethod(operationName = "GetNewYearsEve", action = "http://www.27seconds.com/Holidays/US/Dates/GetNewYearsEve")
    @RequestWrapper(localName = "GetNewYearsEve", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetNewYearsEve")
    @ResponseWrapper(localName = "GetNewYearsEveResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetNewYearsEveResponse")
    @WebResult(name = "GetNewYearsEveResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getNewYearsEve(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Abraham Lincoln's Birthday.
     */
    @WebMethod(operationName = "GetAbrahamLincolnsBirthday", action = "http://www.27seconds.com/Holidays/US/Dates/GetAbrahamLincolnsBirthday")
    @RequestWrapper(localName = "GetAbrahamLincolnsBirthday", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetAbrahamLincolnsBirthday")
    @ResponseWrapper(localName = "GetAbrahamLincolnsBirthdayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetAbrahamLincolnsBirthdayResponse")
    @WebResult(name = "GetAbrahamLincolnsBirthdayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getAbrahamLincolnsBirthday(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Good Friday.
     */
    @WebMethod(operationName = "GetGoodFriday", action = "http://www.27seconds.com/Holidays/US/Dates/GetGoodFriday")
    @RequestWrapper(localName = "GetGoodFriday", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetGoodFriday")
    @ResponseWrapper(localName = "GetGoodFridayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetGoodFridayResponse")
    @WebResult(name = "GetGoodFridayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getGoodFriday(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Thanksgiving Day.
     */
    @WebMethod(operationName = "GetThanksgivingDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetThanksgivingDay")
    @RequestWrapper(localName = "GetThanksgivingDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetThanksgivingDay")
    @ResponseWrapper(localName = "GetThanksgivingDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetThanksgivingDayResponse")
    @WebResult(name = "GetThanksgivingDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getThanksgivingDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Halloween Day.
     */
    @WebMethod(operationName = "GetHalloweenDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetHalloweenDay")
    @RequestWrapper(localName = "GetHalloweenDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetHalloweenDay")
    @ResponseWrapper(localName = "GetHalloweenDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetHalloweenDayResponse")
    @WebResult(name = "GetHalloweenDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getHalloweenDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of April Fool's Day.
     */
    @WebMethod(operationName = "GetAprilFoolsDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetAprilFoolsDay")
    @RequestWrapper(localName = "GetAprilFoolsDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetAprilFoolsDay")
    @ResponseWrapper(localName = "GetAprilFoolsDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetAprilFoolsDayResponse")
    @WebResult(name = "GetAprilFoolsDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getAprilFoolsDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Flag Day.
     */
    @WebMethod(operationName = "GetFlagDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetFlagDay")
    @RequestWrapper(localName = "GetFlagDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetFlagDay")
    @ResponseWrapper(localName = "GetFlagDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetFlagDayResponse")
    @WebResult(name = "GetFlagDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getFlagDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Labor Day.
     */
    @WebMethod(operationName = "GetLaborDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetLaborDay")
    @RequestWrapper(localName = "GetLaborDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetLaborDay")
    @ResponseWrapper(localName = "GetLaborDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetLaborDayResponse")
    @WebResult(name = "GetLaborDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getLaborDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Columbus Day.
     */
    @WebMethod(operationName = "GetColumbusDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetColumbusDay")
    @RequestWrapper(localName = "GetColumbusDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetColumbusDay")
    @ResponseWrapper(localName = "GetColumbusDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetColumbusDayResponse")
    @WebResult(name = "GetColumbusDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getColumbusDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Easter.
     */
    @WebMethod(operationName = "GetEaster", action = "http://www.27seconds.com/Holidays/US/Dates/GetEaster")
    @RequestWrapper(localName = "GetEaster", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetEaster")
    @ResponseWrapper(localName = "GetEasterResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetEasterResponse")
    @WebResult(name = "GetEasterResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getEaster(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Martin Luther King Day.
     */
    @WebMethod(operationName = "GetMartinLutherKingDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetMartinLutherKingDay")
    @RequestWrapper(localName = "GetMartinLutherKingDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetMartinLutherKingDay")
    @ResponseWrapper(localName = "GetMartinLutherKingDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetMartinLutherKingDayResponse")
    @WebResult(name = "GetMartinLutherKingDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getMartinLutherKingDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Father's Day.
     */
    @WebMethod(operationName = "GetFathersDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetFathersDay")
    @RequestWrapper(localName = "GetFathersDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetFathersDay")
    @ResponseWrapper(localName = "GetFathersDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetFathersDayResponse")
    @WebResult(name = "GetFathersDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getFathersDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Valentines Day.
     */
    @WebMethod(operationName = "GetValentinesDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetValentinesDay")
    @RequestWrapper(localName = "GetValentinesDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetValentinesDay")
    @ResponseWrapper(localName = "GetValentinesDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetValentinesDayResponse")
    @WebResult(name = "GetValentinesDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getValentinesDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of President's Day.
     */
    @WebMethod(operationName = "GetPresidentsDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetPresidentsDay")
    @RequestWrapper(localName = "GetPresidentsDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetPresidentsDay")
    @ResponseWrapper(localName = "GetPresidentsDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetPresidentsDayResponse")
    @WebResult(name = "GetPresidentsDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getPresidentsDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Black Friday.
     */
    @WebMethod(operationName = "GetBlackFriday", action = "http://www.27seconds.com/Holidays/US/Dates/GetBlackFriday")
    @RequestWrapper(localName = "GetBlackFriday", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetBlackFriday")
    @ResponseWrapper(localName = "GetBlackFridayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetBlackFridayResponse")
    @WebResult(name = "GetBlackFridayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getBlackFriday(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Saint Patrick's Day.
     */
    @WebMethod(operationName = "GetSaintPatricksDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetSaintPatricksDay")
    @RequestWrapper(localName = "GetSaintPatricksDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetSaintPatricksDay")
    @ResponseWrapper(localName = "GetSaintPatricksDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetSaintPatricksDayResponse")
    @WebResult(name = "GetSaintPatricksDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getSaintPatricksDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of New Year.
     */
    @WebMethod(operationName = "GetNewYear", action = "http://www.27seconds.com/Holidays/US/Dates/GetNewYear")
    @RequestWrapper(localName = "GetNewYear", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetNewYear")
    @ResponseWrapper(localName = "GetNewYearResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetNewYearResponse")
    @WebResult(name = "GetNewYearResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getNewYear(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Veteran's Day.
     */
    @WebMethod(operationName = "GetVeteransDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetVeteransDay")
    @RequestWrapper(localName = "GetVeteransDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetVeteransDay")
    @ResponseWrapper(localName = "GetVeteransDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetVeteransDayResponse")
    @WebResult(name = "GetVeteransDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getVeteransDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of George Washington's Birthday.
     */
    @WebMethod(operationName = "GetGeorgeWashingtonsBirthday", action = "http://www.27seconds.com/Holidays/US/Dates/GetGeorgeWashingtonsBirthday")
    @RequestWrapper(localName = "GetGeorgeWashingtonsBirthday", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetGeorgeWashingtonsBirthday")
    @ResponseWrapper(localName = "GetGeorgeWashingtonsBirthdayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetGeorgeWashingtonsBirthdayResponse")
    @WebResult(name = "GetGeorgeWashingtonsBirthdayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getGeorgeWashingtonsBirthday(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Christmas.
     */
    @WebMethod(operationName = "GetChristmasDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetChristmasDay")
    @RequestWrapper(localName = "GetChristmasDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetChristmasDay")
    @ResponseWrapper(localName = "GetChristmasDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetChristmasDayResponse")
    @WebResult(name = "GetChristmasDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getChristmasDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Cinco de Mayo.
     */
    @WebMethod(operationName = "GetCincoDeMayo", action = "http://www.27seconds.com/Holidays/US/Dates/GetCincoDeMayo")
    @RequestWrapper(localName = "GetCincoDeMayo", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetCincoDeMayo")
    @ResponseWrapper(localName = "GetCincoDeMayoResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetCincoDeMayoResponse")
    @WebResult(name = "GetCincoDeMayoResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getCincoDeMayo(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Memorial Day.
     */
    @WebMethod(operationName = "GetMemorialDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetMemorialDay")
    @RequestWrapper(localName = "GetMemorialDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetMemorialDay")
    @ResponseWrapper(localName = "GetMemorialDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetMemorialDayResponse")
    @WebResult(name = "GetMemorialDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getMemorialDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );

    /**
     * Get the date of Mother's Day.
     */
    @WebMethod(operationName = "GetMothersDay", action = "http://www.27seconds.com/Holidays/US/Dates/GetMothersDay")
    @RequestWrapper(localName = "GetMothersDay", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetMothersDay")
    @ResponseWrapper(localName = "GetMothersDayResponse", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/", className = "com._27seconds.holidays.us.dates.GetMothersDayResponse")
    @WebResult(name = "GetMothersDayResult", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
    public javax.xml.datatype.XMLGregorianCalendar getMothersDay(
        @WebParam(name = "year", targetNamespace = "http://www.27seconds.com/Holidays/US/Dates/")
        int year
    );
}
